CREATE TABLE IF NOT EXISTS day_planner(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text_planner TEXT NOT NULL,
    ok INTEGER NOT NULL DEFAULT 0,
    make DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);